--
-- Table structure for table `idd_person`
--

CREATE TABLE IF NOT EXISTS `Movies` (
  `id` int NOT NULL primary key,
  `title` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `video` varchar(1000) NOT NULL,
  `poster_path` varchar(1000) NOT NULL,
  `overview` varchar(10000) NOT NULL,
  `release_date` varchar(255) NOT NULL,
  `vote_average` float NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `idd_person`
--

INSERT INTO `Movies` (`id`, `title`, `type`, `video`,`poster_path`,`overview`,`release_date`,`vote_average`) VALUES
(616037,"Thor: Love and Thunder","popular","http://2embed.org/embed/tt10648342","http://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg","After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.","2022-07-06",6.7),
(507086,"Jurassic World Dominion","popular","http://2embed.org/embed/tt8041270","http://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg","Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.","2022-06-01",7.1),
(438148,"Minions: The Rise of Gru","popular","http://2embed.org/embed/tt5113044","http://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg","A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.","2022-06-29",7.5),
(361743,"Top Gun: Maverick","popular","http://2embed.org/embed/tt1745960","http://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg","After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.","2022-05-24",8.3),
(756999,"The Black Phone","popular","http://2embed.org/embed/tt7144666","http://image.tmdb.org/t/p/w500/p9ZUzCyy9wRTDuuQexkQ78R2BgF.jpg","Finney Shaw, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.","2022-06-22",8.0),
(718789,"Lightyear","popular","http://2embed.org/embed/tt10298810","http://image.tmdb.org/t/p/w500/ox4goZd956BxqJH6iLwhWPL9ct4.jpg","Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.","2022-06-15",7.3),
(453395,"Doctor Strange in the Multiverse of Madness","popular","http://2embed.org/embed/tt9419884","http://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg","Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.","2022-05-04",7.5),
(725201,"The Gray Man","popular","http://2embed.org/embed/tt1649418","http://image.tmdb.org/t/p/w500/8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg","When a shadowy CIA agent uncovers damning agency secrets, he's hunted across the globe by a sociopathic rogue operative who's put a bounty on his head.","2022-07-13",7.0),

(854467,"Indemnity","action","http://2embed.org/embed/tt7914022","http://image.tmdb.org/t/p/w500/tVbO8EAbegVtVkrl8wNhzoxS84N.jpg","An ex-fireman with PTSD goes on the run when accused of a crime he doesn't even remember committing, leading him down a rabbit hole of conspiracy to the highest degree.","2022-02-11",6.7),
(836225,"The Exorcism of God","action","http://2embed.org/embed/tt10362566","http://image.tmdb.org/t/p/w500/hangTmbxpSV4gpHG7MgSlCWSSFa.jpg","An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.","2022-03-11",7.1),
(924482,"The Ledge","action","http://2embed.org/embed/tt6805938","http://image.tmdb.org/t/p/w500/mKFT6Q7PjrRLYuPLfmH4WLCXOiD.jpg","A rock climbing adventure between two friends turns into a terrifying nightmare. After Kelly captures the murder of her best friend on camera, she becomes the next target of a tight-knit group of friends who will stop at nothing to destroy the evidence and anyone in their way. Desperate for her safety, she begins a treacherous climb up a mountain cliff and her survival instincts are put to the test when she becomes trapped with the killers just 20 feet away.","2022-02-18",6.2),
(728366,"Borrego","action","http://2embed.org/embed/tt12676006","http://image.tmdb.org/t/p/w500/kPzQtr5LTheO0mBodIeAXHgthYX.jpg","A young botanist relocates to a small desert town to study an invasive plant species. While out on research, she comes to the aid of a downed plane only to find herself taken captive by an inexperienced drug mule who forces her to lead a trek across the sweltering desert to his drop. A local sheriff is drawn into the hunt as his rebellious daughter sets out to find the missing botanist, all the while being pursued by a local drug receiver.","2022-01-14",6.1),

(919355,"Dragon Knight","fiction","http://2embed.org/embed/tt13117446","http://image.tmdb.org/t/p/w500/uSMJbYhaEpQtF9vkMhpgljc0CA4.jpg","Many years after the war has been lost, and all the dragons slain, a lone knight travels the lands of Agonos seeking to raise an army against the demon lord Abaddon. When a healer's vision reveals that one dragon still lives, and together with an eager young squire, the knight sets off in search of the fabled creature. As the armies of Abaddon descend on the human kingdoms, the dragon is their last hope of fending off the horde, before it lays waste to the lands of men.","2022-03-21",6.6),
(634649,"Spider-Man: No Way Home","fiction","http://2embed.org/embed/tt10872600","http://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg","Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.","2021-12-15",8.1),
(759175,"The Princess","fiction","http://2embed.org/embed/tt13406136","http://image.tmdb.org/t/p/w500/9pCoqX24a6rE981fY1O3PmhiwrB.jpg","A beautiful, strong-willed young royal refuses to wed the cruel sociopath to whom she is betrothed and is kidnapped and locked in a remote tower of her father’s castle. With her scorned, vindictive suitor intent on taking her father’s throne, the princess must protect her family and save the kingdom.","2022-06-16",7.1),
(961484,"Last Seen Alive","fiction","http://2embed.org/embed/tt15004136","http://image.tmdb.org/t/p/w500/qvqyDj34Uivokf4qIvK4bH0m0qF.jpg","After Will Spann's wife suddenly vanishes at a gas station, his desperate search to find her leads him down a dark path that forces him to run from authorities and take the law into his own hands.","2022-05-19",6.5);
  


CREATE TABLE IF NOT EXISTS `Actors` (
  `id` int NOT NULL primary key,
  `movie_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `known_for_department` varchar(255) NOT NULL,
  `profile_path` varchar(1000) NOT NULL,
  `character` varchar(255) NOT NULL,
  `biography` varchar(5000) NOT NULL,
  `birthday` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `Actors` (`id`, `movie_id`, `known_for_department`, `name`,`profile_path`,`character`,`biography`,`birthday`) VALUES
(74568,616037,"Acting","Chris Hemsworth","http://image.tmdb.org/t/p/w500/jpurJ9jAcLCYjgHHfYF32m3zJYm.jpg","Thor Odinson","Chris Hemsworth (born 11 August 1983) is an Australian actor. He is best known for his roles as Kim Hyde in the Australian TV series Home and Away (2004) and as Thor in the Marvel Cinematic Universe films Thor (2011), The Avengers (2012), Thor: The Dark World (2013), Avengers: Age of Ultron (2015), Thor: Ragnarok (2017), Avengers: Infinity War (2018), Avengers: Endgame (2019), and Thor: Love and Thunder (2022). He has also appeared in the science fiction action film Star Trek(2009), the thriller adventure A Perfect Getaway (2009), the horror comedy The Cabin in the Woods (2012), the dark fantasy action film Snow White and the Huntsman (2012), the war film Red Dawn (2012) and the biographical sports drama film Rush (2013).\n\nDescription above from the Wikipedia article Chris Hemsworth, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1983-08-11"),
(524,616037,"Acting","Natalie Portman","http://image.tmdb.org/t/p/w500/edPU5HxncLWa1YkgRPNkSd68ONG.jpg","Jane Foster / The Mighty Thor","Natalie Portman (born Neta-Lee Hershlag, June 9, 1981) is an actress with dual American and Israeli citizenship. Her first role was in the 1994 action thriller Léon: The Professional, opposite Jean Reno. She was later cast as Padmé Amidala in the Star Wars prequel trilogy (released in 1999, 2002 and 2005).\n\nBorn in Jerusalem to an Israeli father and American mother, Portman grew up in the eastern United States from the age of three. She studied dancing and acting in New York, and starred in Star Wars: Episode I – The Phantom Menace while still at high school on Long Island. In 1999, Portman enrolled at Harvard University to study psychology, alongside her work as an actress; she completed a bachelor's degree in 2003. During her studies she starred in a second Star Wars film and opened in New York City's The Public Theater production of Anton Chekhov's The Seagull in 2001.\n\nPortman won a Golden Globe and was nominated for an Academy Award for starring in the 2004 drama Closer, appeared in Star Wars: Episode III – Revenge of the Sith the following year, and won a Constellation Award for Best Female Performance and the Saturn Award for Best Actress for her starring role in the political thriller V for Vendetta (2006). She played leading roles in the historical dramas Goya's Ghosts (2006) and The Other Boleyn Girl (2008), and also appeared in Thor (2011) and its 2013 sequel. In 2010, Portman starred in the psychological thriller film Black Swan. Her performance received widespread critical acclaim and she earned her first Academy Award for Best Actress, her second Golden Globe Award, the SAG Award, the BAFTA Award and the BFCA Award in 2011. In 2016, she portrayed First Lady Jacqueline Kennedy in the biographical drama Jackie. She was nominated for an Academy Award, a BAFTA Award, a Golden Globe Award, a Screen Actors Guild Award and won the BFCA for Best Actress. In May 2008, Portman served as the youngest member of the 61st Annual Cannes Film Festival jury. The same year she directed a segment of the collective film New York, I Love You. Her first feature film as a director, A Tale of Love and Darkness, was released in 2015.","1981-06-09"),
(3894,616037,"Acting","Christian Bale","http://image.tmdb.org/t/p/w500/qCpZn2e3dimwbryLnqxZuI88PTi.jpg","Gorr the God Butcher","Christian Charles Philip Bale (born 30 January 1974) is an English actor. Known for his versatility and recurring physical transformations to play his roles, he has been a leading man in films of several genres. Bale is the recipient of various accolades, including an Academy Award and two Golden Globe Awards. Time magazine included him on its list of the 100 most influential people in the world in 2011.\n\nBorn in Wales to English parents, Bale had his breakthrough role at age 13 in Steven Spielberg's 1987 war film Empire of the Sun. After more than a decade of performing in leading and supporting roles in films, he gained wider recognition for his portrayals of serial killer Patrick Bateman in the black comedy American Psycho (2000) and the titular role in the psychological thriller The Machinist (2004). In 2005, Bale played superhero Batman in Batman Begins and reprised the role in the sequels The Dark Knight (2008) and The Dark Knight Rises (2012), garnering acclaim for his performance in the trilogy, which is one of the highest-grossing film franchises.\n\nBale continued in starring roles in a range of films outside his work as Batman, including the period drama The Prestige (2006), the action film Terminator Salvation (2009), the crime drama Public Enemies (2009), the epic film Exodus: Gods and Kings (2014) and the historical drama The Promise (2016). For his portrayal of boxer Dicky Eklund in the 2010 biographical film The Fighter, Bale won an Academy Award and a Golden Globe Award. Further Academy Award and Golden Globe Award nominations came in subsequent years for his work in the black comedy American Hustle (2013) and the biographical dramedies The Big Short (2015) and Vice (2018). Bale's roles as politician Dick Cheney in Vice and race car driver Ken Miles in the sports drama Ford v Ferrari (2019) respectively earned him a second win and a fifth nomination at the Golden Globe Awards.","1974-01-30"),
(62561,616037,"Acting","Tessa Thompson","http://image.tmdb.org/t/p/w500/fycqdiiM6dsNSbnONBVVQ57ILV1.jpg","King Valkyrie","Tessa Lynne Thompson (born October 3, 1983) is an American actress, producer, singer, and songwriter. She began her professional acting career with the Los Angeles Women's Shakespeare Company while studying at Santa Monica College. She appeared in productions of The Tempest and Romeo and Juliet, the latter of which earned her a NAACP Theatre Award nomination. Her breakthrough came with leading roles in Tina Mabry's independent drama film Mississippi Damned (2009) and Tyler Perry's drama film For Colored Girls (2010).  Thompson was was raised between Los Angeles and Brooklyn, New York. Her father, singer-songwriter Marc Anthony Thompson, is of Afro-Panamanian descent and is the founder of the musical collective Chocolate Genius, Inc. Her mother has white and Mexican ancestry. She has a younger half-sister, Zsela, who is a singer and songwriter.\n\nThompson attended Santa Monica High School, where she played Hermia in a student production of A Midsummer Night's Dream. She then attended Santa Monica College (SMC), where she studied cultural anthropology and is a member of the alma mater. While at SMC, she also attended lectures by Lisa Wolpe of the Los Angeles Women's Shakespeare Company (LAWSC).\n\nThis page is based on a Wikipedia article written by contributors. Text is available under the CC BY-SA 4.0 license; additional terms may apply.","1983-10-03"),
(55934,616037,"Directing","Taika Waititi","http://image.tmdb.org/t/p/w500/zCLBXGo5BS2e27srDBa5WpRnKul.jpg","Korg / Old Kronan God (voice)","Taika David Cohen ONZM (born 16 August 1975), known professionally as Taika Waititi, is a New Zealand film and television director, producer, screenwriter, actor, and comedian. He is the recipient of an Academy Award, BAFTA Award and a Grammy Award, and has been nominated for two Primetime Emmy Awards. His feature films Boy (2010) and Hunt for the Wilderpeople (2016) have each been the top-grossing New Zealand film.\n\nWaititi's 2004 short film Two Cars, One Night earned him an Academy Award nomination for Best Live Action Short Film. He co-directed and starred in the horror comedy film What We Do in the Shadows (2014) with Jemaine Clement, which was adapted into a television series of the same name (2019–present). The series has been nominated for the Primetime Emmy Award for Outstanding Comedy Series. His most recent directing credits include the superhero film Thor: Ragnarok (2017) and the black comedy film Jojo Rabbit (2019), the latter of which he also wrote and starred in as an imaginary Hitler. Jojo Rabbit received six Academy Award nominations and won for Best Adapted Screenplay. Furthermore, Waititi earned a Grammy Award for producing the film's soundtrack. In addition to directing an episode of the television series The Mandalorian (2019–present), he also voices the character IG-11, for which he garnered a Primetime Emmy Award nomination for Outstanding Character Voice-Over Performance.","1975-08-16"),
(934,616037,"Acting","Russell Crowe","http://image.tmdb.org/t/p/w500/mGTtPuwE8OR00tkJGmVLJmt8KpW.jpg","Zeus","Russell Ira Crowe (born 7 April 1964) is an actor, director, musician, and singer. He was born in New Zealand, spent 10 years of his childhood in Australia, and moved there permanently at age 21. He came to international attention for his role as Roman General Maximus Decimus Meridius in the epic historical film Gladiator (2000), for which he won an Academy Award, Broadcast Film Critics Association Award, Empire Award, and London Film Critics Circle Award for Best Leading Actor, along with 10 other nominations in the same category.\n\nCrowe's other award-winning performances include tobacco firm whistle-blower Jeffrey Wigand in the drama film The Insider (1999) and John F. Nash in the biopic A Beautiful Mind (2001). He has also starred in films such as the drama Romper Stomper (1992), the mystery-detective thriller L.A. Confidential (1997), the epic war film Master and Commander: The Far Side of the World (2003), the boxing drama Cinderella Man (2005), the Western 3:10 to Yuma (2007), the crime drama American Gangster (2007), the thriller-drama State of Play (2009), and Robin Hood (2010).\n\nCrowe later starred in the musical drama Les Misérables (2012), as Jor-El in the superhero epic Man of Steel (2013), the biblical fantasy drama Noah (2014), and the action comedy The Nice Guys (2016). In 2014, he made his directorial debut with the drama The Water Diviner, in which he also starred. He has earned several accolades, including a star on the Hollywood Walk of Fame, two Golden Globe Awards, one BAFTA, and one Academy Award out of three consecutive nominations (1999, 2000, and 2001). He has been the co-owner of the National Rugby League (NRL) team South Sydney Rabbitohs since 2006.","1964-04-07"),
(5981,616037,"Acting","Jaimie Alexander","http://image.tmdb.org/t/p/w500/hO8ADSA0sKnO3VkPjwA7MZE7r5W.jpg","Sif","Jaimie Alexander (born March 12, 1984) is an American actress known for portraying Jessi on the TV series Kyle XY and Sif in the 2011 superhero film Thor, it's 2013 sequel, Thor: The Dark World, and Agents of S.H.I.E.L.D.. Since 2015 she stars in the NBC series Blindspot.\n\nJaimie Alexander was born in Greenville, South Carolina, and moved to Grapevine, Texas when she was four years old. She is the only girl in a family of five children. Alexander first got into acting in grade school, where she took theater for fun. Alexander stated that she was actually kicked out of theater when she was in high school because she could not sing, so she instead went into sports. When she was 17, she substituted for a friend at a meeting with a scouting agency and she met her manager, Randy James, who sent her some scripts. After her graduation from Colleyville Heritage High School, a year and a half later, she moved to Los Angeles to pursue her acting career.\n\nLicensed under CC-BY-SA, full list of contributors on Wikipedia.","1984-03-12"),
(543530,616037,"Acting","Dave Bautista","http://image.tmdb.org/t/p/w500/ymn6iQBJbQZN6BYI60YJDXVP4gF.jpg","Drax the Destroyer","Dave Bautista is an American actor and former professional wrestler, mixed martial artist, and bodybuilder.\n\nFrom 2000–2010 and 2013–2014, he was signed to WWE under the ring name Batista, where he became a six-time world champion, winning WWE's World Heavyweight Championship four times and the WWE Championship twice. He holds the record for the longest reign as World Heavyweight Champion at 282 days, and has also won the World Tag Team Championship three times (twice with Ric Flair and once with John Cena) and the WWE Tag Team Championship once (with Rey Mysterio). He was the winner of the 2005 Royal Rumble match and went on to headline WrestleMania 21, one of the top five highest-grossing pay-per-view events in professional wrestling history. When Bautista returned to WWE in 2014, he won the 2014 Royal Rumble match, after which he headlined WrestleMania XXX.\n\nIn August 2012, Bautista signed a contract with Classic Entertainment & Sports to fight in mixed martial arts. He won his MMA debut on October 6, 2012, defeating Vince Lucero via TKO in the first round. He was representing the Philippines during the fight. Bautista first entered the world of acting in 2006. As an actor, Bautista has starred in The Man with the Iron Fists (2012), Riddick (2013), Guardians of the Galaxy (2014), the 24th James Bond film, Spectre (2015), L.A. Slasher (2015), and in the 2016 Kickboxer reboot, Kickboxer: Vengeance. Bautista reprised his role as Drax in Guardians of the Galaxy Vol. 2 (2017) Avengers: Infinity War (2018), Avengers: Endgame (2019) and Thor: Love and Thunder (2022). He has also appeared in several direct-to-video films since 2009.","1969-01-18"),
(543261,616037,"Acting","Karen Gillan","http://image.tmdb.org/t/p/w500/kFLXcFdok3ShDxylr3WNreQphQm.jpg","Nebula","Karen Gillan (born 28 November 1987) is a Scottish actress, director, and screenwriter from Inverness, Scotland. She played the role of Amy Pond, companion to the Eleventh Doctor, in the BBC One science fiction series Doctor Who (2010–2013). In film, she portrayed Nebula in the Marvel Cinematic Universe films Guardians of the Galaxy (2014) and Guardians of the Galaxy Vol. 2 (2017), Avengers: Infinity War (2018), and Avengers: Endgame (2019), and also played Ruby Roundhouse in the box-office hit Jumanji: Welcome to the Jungle (2017).\n\nIn 2018, she released her first feature film as writer and director, titled The Party's Just Beginning.\n\nDescription above from the Wikipedia article Karen Gillan, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1987-11-28"),

(73457,507086,"Acting","Chris Pratt","http://image.tmdb.org/t/p/w500/83o3koL82jt30EJ0rz4Bnzrt2dd.jpg","Owen Grady","Christopher Michael Pratt (born 21 June 1979) is an American actor, known for starring in both television and action films. He rose to prominence for his television roles, particularly in the NBC sitcom Parks and Recreation (2009–2015), for which he received critical acclaim and was nominated for the Critics' Choice Television Award for Best Supporting Actor in a Comedy Series in 2013. He also starred earlier in his career as Bright Abbott in The WB drama series Everwood (2002–2006) and had roles in Wanted (2008), Jennifer's Body (2009), Moneyball (2011), The Five-Year Engagement (2012), Zero Dark Thirty (2013), Delivery Man (2013), and Her (2013).\n\nPratt achieved leading man status in 2014, starring in two critically and commercially successful films: The Lego Movie as Emmet Brickowski, and Marvel Studios' Guardians of the Galaxy as Star-Lord. He starred in Jurassic World (2015) and Jurassic World: Fallen Kingdom (2018), and he reprised his Marvel role in Guardians of the Galaxy Vol. 2 (2017), Avengers: Infinity War (2018), Avengers: Endgame (2019), and the planned Guardians of the Galaxy Vol. 3. Meanwhile, in 2016 he was part of an ensemble cast in The Magnificent Seven and the male lead in Passengers.\n\nDescription above is from the Wikipedia article Chris Pratt, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1979-06-21"),
(18997,507086,"Acting","Bryce Dallas Howard","http://image.tmdb.org/t/p/w500/qQX1rhQaJ1G8eMG2RknFKiXfNRc.jpg","Claire Dearing","Bryce Dallas Howard (born March 2, 1981) is an American actress and director. She is the eldest daughter of actor and filmmaker Ron Howard and landed her first major film role in the 2004 M. Night Shyamalan feature The Village (2004). She received a Golden Globe Award nomination for her performance in the TV movie As You Like It. She also stars as Claire Dearing in the 2015 blockbuster Jurassic World.","1981-03-02"),
(4784,507086,"Acting","Laura Dern","http://image.tmdb.org/t/p/w500/gB9PnGEvxKg33OSlcqptQwTBwPE.jpg","Dr. Ellie Sattler","Laura Elizabeth Dern (born February 10, 1967) is an American actress and filmmaker. She is the recipient of numerous accolades, including an Academy Award, a Primetime Emmy Award, and five Golden Globe Awards. Born to actors Bruce Dern and Diane Ladd, Dern embarked on an acting career in the 1980s and rose to some prominence for her performances in Mask (1985) and David Lynch's Blue Velvet (1986) and Wild at Heart (1990). She received an Academy Award nomination for her portrayal of the titular orphan in the drama film Rambling Rose (1991) and achieved international recognition for her role in Steven Spielberg's adventure film Jurassic Park (1993), a role that she reprised in the 2001 sequel Jurassic Park III.\n\nAfter winning two Golden Globe Awards for her performances as Katherine Harris in the television film Recount (2008) and Amy Jellicoe in the comedy-drama series Enlightened (2011–2013), Dern garnered her second Academy Award nomination for her work in the biopic Wild (2014). In 2017, she began starring as Renata Klein in the drama series Big Little Lies, winning a Primetime Emmy Award and Golden Globe Award, and reunited with David Lynch for Twin Peaks: The Return. She has since played supporting roles in the films Star Wars: The Last Jedi (2017), Marriage Story (2019), and Little Women (2019). Her performance in Marriage Story won her an Academy Award and Golden Globe Award, both for Best Supporting Actress.\n\nDescription above from the Wikipedia article Laura Dern, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1967-02-10"),
(4785,507086,"Acting","Jeff Goldblum","http://image.tmdb.org/t/p/w500/ceSmXnD0FUSTaq2WIrnZu9caL0t.jpg","Dr. Ian Malcolm","Jeffrey Lynn Goldblum (born October 22, 1952) is an American actor and musician. He has starred in some of the highest-grossing films of his era, such as Jurassic Park (1993) and Independence Day (1996), as well as their respective sequels, The Lost World: Jurassic Park (1997) and Jurassic World: Fallen Kingdom (2018), and Independence Day: Resurgence (2016).\n\nGoldblum also starred in films including Invasion of the Body Snatchers (1978), The Big Chill (1983), and Into the Night (1985), before coming to wider attention as Seth Brundle in The Fly (1986), which earned him a Saturn Award for Best Actor. His other films include The Adventures of Buckaroo Banzai Across the 8th Dimension (1984), The Tall Guy (1989), Deep Cover (1992), Powder (1995), The Prince of Egypt (1998), Cats & Dogs (2001), Igby Goes Down (2002), The Life Aquatic with Steve Zissou (2004), Adam Resurrected (2008), Le Week-End (2013), The Grand Budapest Hotel (2014), and Thor: Ragnarok (2017).\n\nGoldblum has also starred in several TV series, including the eighth and ninth seasons of Law & Order: Criminal Intent as Zack Nichols. He directed the short film Little Surprises, which was nominated for the Academy Award for Best Live Action Short Film.\n\nDescription above is from the Wikipedia article Jeff Goldblum, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1952-10-22"),
(4783,507086,"Acting","Sam Neill","http://image.tmdb.org/t/p/w500/bNZ03phkLewj8eUR6mGbKZ7jtmv.jpg","Dr. Alan Grant","Nigel John Dermot Sam Neill (born 14 September 1947) is a New Zealand actor. He is perhaps best known for his starring role as paleontologist Dr Alan Grant in Jurassic Park and Jurassic Park III. He has also had a number of high-profile roles including: the lead in Reilly, Ace of Spies, the adult Damien in Omen III: The Final Conflict, Merlin in the miniseries Merlin, Captain Vasily Borodin in The Hunt for Red October, Lord Friedrich Hoffman in Snow White: A Tale of Terror, and Alisdair Stewart in The Piano.\n\nMost recently he played Cardinal Thomas Wolsey in the Peace Arch Entertainment production for Showtime, The Tudors.\n\nDescription above from the Wikipedia article Sam Neill, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1947-09-14"),

(4495,438148,"Acting","Steve Carell","http://image.tmdb.org/t/p/w500/dzJtsLspH5Bf8Tvw7OQC47ETNfJ.jpg","Gru (voice)","Steven John Carell (born August 16, 1962) is an American actor and comedian. He played Michael Scott in The Office (2005–2011; 2013), NBC’s adaptation of the British series created by Stephen Merchant and Ricky Gervais, where Carell also worked as an occasional producer, writer and director. Carell has received numerous accolades for his performances in both film and television, including the Golden Globe Award for Best Actor – Television Series Musical or Comedy for his work on The Office. He was recognized as America's Funniest Man\ by Life magazine.\n\nCarell gained recognition as a correspondent on The Daily Show with Jon Stewart from 1999 to 2005. He went on to star in several comedy films, including Anchorman: The Legend of Ron Burgundy (2004) and its 2013 sequel, as well as The 40-Year-Old Virgin (2005), Evan Almighty (2007), Get Smart (2008), Date Night (2010), Crazy, Stupid, Love (2011), and The Way, Way Back (2013). He also voice acted in Over the Hedge (2006), Horton Hears a Who! (2008) and the Despicable Me franchise (2010–present).\n\nCarell began to shift into more dramatic roles in the 2010s","1962-08-16"),
(124747,438148,"Acting","Pierre Coffin","http://image.tmdb.org/t/p/w500/5HojYPP34c4agydy7D90apCMNHn.jpg","Kevin / Stuart / Bob / Minions (voice)","From Wikipedia, the free encyclopedia.  \n\nPierre Coffin, born in 1967, is a French animator and director. He was trained at the Gobelins in Paris and started to work at Amblimation, the 2D London based facility, where he worked on the Steven Spielberg-executive-produced We are Back! A Dinosaur Story. He then started as a freelance animator in the French CGI studio Ex Machina where he worked as animator, animation supervisor, and eventually director. Afterwards, he started to collaborate with Passion Pictures Paris and Mac Guff where in 2010 he completed, with Chris Renaud, the feature CGI animated movie Despicable Me for Universal. He also provided voices for a few of the minor characters. Peter Coffin has created animations named Pings ( animations of penguins being hurt or killed).\n\nDescription above from the Wikipedia article Pierre Coffin, licensed under CC-BY-SA, full list of contributors on Wikipedia.","1967-03-15"),
(59919,438148,"Acting","Russell Brand","http://image.tmdb.org/t/p/w500/fJ9oOcEeBzDT4hHFh0GNogV6l7l.jpg","Dr. Nefario (voice)","British comedian, actor, columnist, author and TV & radio personality.\n\nBrand achieved mainstream fame in the UK for presenting a Big Brother spin-off, Big Brother's Big Mouth, and for his radio show, among other television series and award ceremonies. He is noted for various controversies that have surrounded him in the British media, such as the 2008 prank calls that led to his resignation from the BBC.","1975-06-04"),
(1903,438148,"Acting","Alan Arkin","http://image.tmdb.org/t/p/w500/mhACkTNrnwR4E115h8EfCZ263zH.jpg","Wild Knuckles (voice)","Alan Wolf Arkin (born March 26, 1934) is an American actor, director, musician and singer. He is known for starring in such films as Wait Until Dark, The Russians Are Coming, the Russians Are Coming, The Heart is a Lonely Hunter, Catch-22, The In-Laws, Edward Scissorhands, Glengarry Glen Ross, Marley & Me, Argo and Little Miss Sunshine, for which he won an Academy Award for Best Supporting Actor in 2006. He is the father of actors Adam Arkin, Anthony Arkin, and Matthew Arkin.","1934-03-26"),
(40036,438148,"Acting","Taraji P. Henson","http://image.tmdb.org/t/p/w500/rxnEvzGlRBsE94s7lC4cMAiLluH.jpg","Belle Bottom (voice)","Taraji P. Henson (born September 11, 1970) is an American actress, producer and singer. She studied acting at Howard University and began her Hollywood career as guest star on several television shows before making her breakthrough in the movie Baby Boy (2001). In 2005, she starred in Hustle &amp; Flow and played Queenie in David Fincher's The Curious Case of Benjamin Button (2008), for which she received an Academy Award nomination.\n\nIn 2016, Time named Henson one of the 100 most influential people in the world on the annual Time 100 list. Henson also released an autobiography titled Around The Way Girl.","1970-09-11");